docs/AboutUs.md
docs/team/kenghian.md

Update Keng Hian's About Us page

---

docs/AboutUs.md
docs/team/green-tea-123.md

Docs: Update Jun Boon's About Us page

---

README.md

[W7 tP task] Update README page to match your project

---

docs/_config.yml
docs/_sass/minima/_base.scss

[W7 tP task] Update site-wide settings to match your project

---

docs/DeveloperGuide.md

Update DG Product Scope to match TalentConnect

---

docs/DeveloperGuide.md

Update DG "must have" user stories of TC

---

docs/DeveloperGuide.md

Update DG use cases for screen job

---

docs/DeveloperGuide.md

Add "Add contact" usecase

---

codecov.yml

chore: Add default codecov.yml

chore: Add default codecov.yml

---

src/main/java/seedu/address/model/company/BillingDate.java
src/main/java/seedu/address/model/company/Company.java
src/main/java/seedu/address/model/company/CompanyName.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/ui/CompanyCard.java
src/main/java/seedu/address/ui/CompanyListPanel.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/java/seedu/address/ui/PersonListPanel.java
src/main/resources/view/CompanyListCard.fxml
src/main/resources/view/CompanyListPanel.fxml
src/test/java/seedu/address/model/company/BillingDateTest.java
src/test/java/seedu/address/model/company/CompanyNameTest.java
src/test/java/seedu/address/model/company/CompanyTest.java
src/test/java/seedu/address/testutil/CompanyBuilder.java
src/test/java/seedu/address/testutil/TypicalCompanies.java

Branch add company class

---

src/main/java/seedu/address/ui/JobCard.java

Job Card UI display Salary with formatted string

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/Mode.java
src/main/java/seedu/address/logic/commands/AddJobCommand.java
src/main/java/seedu/address/logic/commands/CommandResult.java
src/main/java/seedu/address/logic/commands/ListCompanyCommand.java
src/main/java/seedu/address/logic/commands/ListJobCommand.java
src/main/java/seedu/address/model/Context.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/MainWindow.java

- closes #64
- I gave it some thought, I think this is a slightly better implementation than the current version
- ModelManger has a static field variable `context`, which is updated when methods that require Ui changes are called (e.g. `updateFilteredList`, `addJob`)
- Can think of `context` as last changed entity
- This approach loses some flexibility as we Ui changes no longer explicitly specify by each command
- I gave up on the approach specified in the issue above as I could not figure out how exactly achieve that without an overhaul

[KH1] Tracks context in ModelManager to update Ui

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/ListCompanyCommand.java
src/main/java/seedu/address/logic/commands/ListContactCommand.java
src/main/java/seedu/address/logic/commands/ListJobCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/ListContactCommandTest.java
src/test/java/seedu/address/logic/commands/ListJobCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

[KH1] Support two word ListComands

---

src/main/java/seedu/address/commons/exceptions/NotImplementedException.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddCompanyCommand.java
src/main/java/seedu/address/logic/commands/AddContactCommand.java
src/main/java/seedu/address/logic/commands/AddJobCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddCompanyCommandParser.java
src/main/java/seedu/address/logic/parser/AddContactCommandParser.java
src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
src/test/java/seedu/address/logic/parser/AddContactCommandParserTest.java
src/test/java/seedu/address/testutil/PersonUtil.java

- close #78 
- Implemented template`<T>` in `AddCommand` as discussed this afternoon

Support two word AddCommands

---

src/main/java/seedu/address/logic/commands/AddCompanyCommand.java
src/main/java/seedu/address/logic/parser/AddCompanyCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/test/java/seedu/address/logic/commands/AddCompanyCommandTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

closes #48 
Please merge Keng Hian's 3 previous PRs before merging mine.

Branch add company command

---

src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml

* closes #101 
* Will need to discuss before merging
* Display all list is a HBox
* Remove all code relating to `context`

feat: Display all 3 lists together in UI

---

src/main/java/seedu/address/logic/commands/MatchCommand.java
src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/MatchCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/job/Job.java
src/main/java/seedu/address/model/job/UniqueJobList.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedJob.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/test/java/seedu/address/logic/commands/AddCompanyCommandTest.java
src/test/java/seedu/address/logic/commands/AddContactCommandTest.java
src/test/java/seedu/address/testutil/JobBuilder.java

> It is currently pointing to `branch-ui-display-three-lists` for better review experience
* @wassilililily @Green-Tea-123 For your review, please
* @AlekKwek18 @Quasant For your information, please
* Note:
* closes #108
* Will add corresponding test in the future #110 
* Simplify Class Diagram : `[Person] <--(matches, *)------(match, 1)--> [Job]`
* Currently it only save data to json file after match command (for my testing)
* the association does not load from json for now, I presume @Quasant will handle the rest?
* I am using `<COMPANY_NAME>::<JOB_NAME>` as job identifier (for establishing association)
* I am using contact name as contact identifier for ease of implementation, I have created an issue #109 for tracking
* Added necessary `setJob()` functions to update Job's matches

Implement MatchCommand

---

src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/job/Job.java
src/main/java/seedu/address/model/job/JobCompany.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedJob.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/main/java/seedu/address/ui/JobCard.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

closes #90 
This integrates the job and company classes by having the name of the company be an attribute of a job. The check for company existence is implemented in the model's addJob function. This handles all of the existence checking when loading from save as well. I determined that company need not have a collection of jobnames as the model could know if a job was from a company if it just compared the company's name to the companyname in job.
Potential bug to fix:
When I throw the CompanyNotFoundException in model, the exception is caught and displayed in the addressbook. However, the terminal still displays an exception called TargetInvocationException that I'm not sure of the origin.

Branch integrate job company easy way

---

src/main/java/seedu/address/logic/commands/MatchCommand.java
src/main/java/seedu/address/logic/parser/MatchCommandParser.java

Just some simple changes to JavaDoc

style: Fix MatchComand JavaDoc

---

src/main/java/seedu/address/logic/commands/DeleteCompanyCommand.java

Fix bug in delete company's success message

---

build.gradle

Apparently this is a task, I saw it from the tP dashboard. 
Just need approval from any 2 of you.

chore: Enable assertion in build.gradle

---

docs/team/kenghian.md

Hi all, I have updated my portfolio, you may use this information to assist you with alpha-testing the features I have implemented. 
For your assistance, please.

docs: Update KH portfolio as of v1.4

---

docs/DeveloperGuide.md
docs/diagrams/ArchitectureSequenceDiagram.puml
docs/diagrams/DeleteSequenceDiagram.puml
docs/team/alekkwek18.md

- Modified UML diagram to replace DeleteCommand with DeleteContactCommand for improved specificity.
- Updated sequence and participant names in the diagram to reflect the change from a generic delete command to one targeting contact deletion.
- Ensured consistency in naming across Logic and Model components.
This update clarifies the intent and functionality of the DeleteContactCommand in the system’s UML representation.

Update DeleteCommand UML In DG

---

src/main/java/seedu/address/logic/commands/MatchCommand.java
src/main/java/seedu/address/logic/commands/UnmatchCommand.java
src/main/java/seedu/address/logic/parser/AddJobCommandParser.java
src/main/java/seedu/address/logic/parser/MatchCommandParser.java
src/main/java/seedu/address/logic/parser/UnmatchCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/job/Job.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedJob.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/JobCard.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/JobListCard.fxml
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/testutil/JobBuilder.java

Made some git commit violations so I started a new branch. 
Click on the issues link and see the comments for screenshots of the changes, feel free to test it out yourself as well.
* Closes #149 
* Closes #148, this applies for match too
* Closes #161 (No screenshots)
* Closes #162 (No video, but you can `git pull origin master` and then do `git checkout branch-remove-references, then play with the match, unmatch and delete job commands)
I don't want to overload the PR so I will stop for now.

Branch remove references

---

src/main/java/seedu/address/logic/commands/ScreenJobCommand.java

Resolve bugs related to screen command from these two issues:
* Closes #164
* Closes #129 
* Closes #141

Fix screen command bug

---

src/main/java/seedu/address/model/skill/Skill.java
src/main/java/seedu/address/model/tag/Tag.java

closes #177 
Just changing the regex to allow spaces in tags and skills which were previously not allowed.

Change skill and tag's regex to allow spaces

---

src/main/java/seedu/address/logic/commands/UnmatchCommand.java
src/main/java/seedu/address/ui/PersonCard.java

Add assertions and logging to unmatch command [WIP]

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/commons/exceptions/SampleDataLoadingException.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAddressBookStorage.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java

closes #189 
closes #195 
Added exception handling for CompanyNotFoundException for both loading from json and loading with a sample address book.

Branch catch exceptions when loading addressbook

---

src/main/java/seedu/address/model/AddressBook.java

fix: Remove company call remove job for necessary teardown

---

src/main/java/seedu/address/logic/Messages.java

feat: Make out of range index error more specific

---

src/main/resources/view/MainWindow.fxml

feat(ui): Add spacing between lists

---

src/main/java/seedu/address/ui/CompanyListPanel.java
src/main/java/seedu/address/ui/JobListPanel.java
src/main/java/seedu/address/ui/PersonListPanel.java

- closes #152 
Dodgy, but hey it works. 
@Green-Tea-123 If you manage to resolve the bug in a "proper" way, feel free to close this PR.

Disable mouse press on lists to cover up our skill issues

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/ScreenCommandParser.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

[Pending #218] feat: Enable commands and entities to be case-insensitive

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/ScreenCommandParser.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

feat: Enable commands and entities to be case-insensitive

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteCompanyCommand.java
src/main/java/seedu/address/logic/commands/DeleteContactCommand.java
src/main/java/seedu/address/logic/commands/DeleteJobCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java

Fix delete command data validation and output message

---

docs/UserGuide.md
src/main/java/seedu/address/commons/exceptions/NotImplementedException.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/storage/JsonAdaptedJob.java
src/main/resources/view/JobListCard.fxml

Deleted artefacts that are not needed, or not touched. 
I removed a bunch of To-do's, so do take note of them. if you wanna do a last min sprint.
Also modified the UG to reflect some changes.
Closes #100

Add final touch ups

---

docs/UserGuide.md

-  closes #287 
-  closes #268

fix: Clarify list commands in UG

---

docs/UserGuide.md

fix: Update UG wording on match to make it clearer

---

docs/UserGuide.md

- closes #331 
@Quasant as discussed, seek your assistance to closes this issue, thanks. 
- closes https://github.com/AY2425S1-CS2103-F13-4/tp/issues/326
Let's close this issue together, they are similar.

Add job behavior not clearly reflected in UG

---

docs/UserGuide.md

- closes #327 
Kindly help to vet my English.

fix: Clarify the purpose of screen command

---

src/main/java/seedu/address/model/company/BillingDate.java

- closes #308 
Does this violate feature freeze?
Ans: No, this is strictly incorrect as date should not involve symbols, plus we specified integer has to be between 1 and 28. 
@Green-Tea-123 Please help to check my changes.

308 pe dtester e incorrect date validation in company

---

docs/UserGuide.md

Group commands in the User Guide by entity (Contact, Company, Job) and provide concise explanations for each. Update examples to improve clarity and consistency. Refine format and layout to enhance readability and align with standardized structure for commands and features.
- Closes #392

docs: Organize User Guide by entity and clarify command usage

---

src/main/java/seedu/address/model/person/Email.java

can check the regex lol
closes #301

Fix email regex
