src/main/java/seedu/address/logic/commands/ListAllCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/main/java/seedu/address/ui/PersonCard.java
src/test/java/seedu/address/logic/commands/ListAllCommandTest.java

Add a new `ListAllCommand` class to list all contacts, companies, and jobs in the address book simultaneously.
This command uses existing predicates to update the filtered lists for each entity, enhancing user experience by consolidating individual list commands.
- Define `ENTITY_WORD` as "all"
- Update all filtered lists using `PREDICATE_SHOW_ALL_PERSONS`, `PREDICATE_SHOW_ALL_COMPANIES`, and `PREDICATE_SHOW_ALL_JOBS`
- Return `CommandResult` with a combined success message
- Remove unused import optional from PersonCard.java 
This feature provides a convenient way for users to view all entities at once, improving accessibility and navigation.
- closes #143

Implement ListAllCommand to list all entities at once

---

src/test/java/seedu/address/logic/parser/ParserUtilTest.java

closes #210
Just updating ParserUtilTest to cover most functions, excluding parseJobRequirements (to be removed) and parseJobDescription (currently no input validation).

Update ParserUtilTest with functions previously not covered by tests

---

src/main/java/seedu/address/model/company/Company.java
src/main/java/seedu/address/model/job/JobCompany.java

closes #205 
The solution to this bug I implemented is quite rudimentary as I didn't want to change `Name`'s equals method. If we decide in the future that we want all names to be case-insensitive, we can either change `Name`'s equals method to be case-insensitive or create a new function in `Name` specifically for case-insensitive comparisons. However, that would require a lot of changes to files that previously used `Name`'s equals method for comparison.

Update Company and JobCompany's comparison methods to ignore case

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/MatchCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/ScreenCommandParser.java
src/main/java/seedu/address/logic/parser/UnmatchCommandParser.java
src/main/java/seedu/address/logic/parser/ViewCompanyCommandParser.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/MatchCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/ScreenCommandParserTest.java

- closes #139 
Do you think invalid index such as "-1" or "one" should throw invalid format error or feedback "index is not non-zero integer"?

Feedback invalid index via default parseIndex() exception instead of invalide format error

---

src/main/java/seedu/address/logic/commands/ScreenCommand.java
src/main/java/seedu/address/logic/commands/ScreenJobCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/test/java/seedu/address/testutil/ModelStub.java

case-insensitive matching
- Update ScreenJobCommand to operate on the entire list of contacts, ignoring any current filters, to ensure all candidates are screened.
- Add new methods `getFullPersonList` and `getFullJobList` to Model interface and implement them in ModelManager to retrieve
unfiltered lists of persons and jobs, allowing comprehensive screening.
- Modify `roleMatchesJobPredicate` to support case-insensitive partial matching by converting both job names and person roles to lowercase, allowing flexible matching.
- Refine usage message for `screen job` command to clarify functionality and improve readability, making
parameters and examples more accessible.
- fixes #207 
- fixes #224 
- fixes #138

Enhance screen command to screen all candidates with case insensitive matching

---

src/main/resources/view/DarkTheme.css
src/main/resources/view/MainWindow.fxml

- Updated `MainWindow.fxml` to add "Contact," "Job," and "Company" labels above their respective panels.
- Applied custom text colors for each label in the CSS file for better visual distinction:
- Contacts label set to light blue (#3498db)
- Jobs label set to green (#2ecc71)
- Companies label set to red (#e74c3c)
- This update enhances the UI, making it easier for users to identify and navigate different sections in Talent Connect.
Resolves issue #236
Before
After

Add labels for Contact, Job, and Company in MainWindow UI

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/ScreenCommandParser.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

- close #150
- close #137
- close #169
- close #156
- Check if operation allowed
- <img src="https://github.com/user-attachments/assets/37101896-79a4-4823-a1f4-10169d09ea89" width="400" /> 
- Check if entity is valid
- <img src="https://github.com/user-attachments/assets/1d2ba9b1-d87b-40f6-a437-b11b32291851" width="400" /> 
- Note
- Not implemented in `Edit` & `Find` as they currently do not check entity, which is inconsistent with the command structure we are using. We should modify them, alternatively we could just disable them. 
- I have not implement this in `ViewCompanyCommand` because it currently does not check entity?
- `Match` & `Unmatch` do not take in entity so it is not needed

[Pending #215] Enforce entity checks on most commands

---

src/main/resources/view/MainWindow.fxml

- Resolve inconsistent padding at the bottom of the Contacts, Jobs, and Companies panels, especially when resizing the window.
- Adjust FXML structure to ensure consistent padding in StackPane and VBox elements.
- Apply explicit padding and alignment properties to prevent collapsing space on resize.
- Ensure a uniform layout for improved user experience , maintaining consistent space around each panel.
Before
After

Fix padding issue at the bottom of panels in Talent Connect

---

src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/main/java/seedu/address/logic/parser/MatchCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/ScreenCommandParser.java
src/main/java/seedu/address/logic/parser/UnmatchCommandParser.java
src/main/java/seedu/address/logic/parser/ViewCompanyCommandParser.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/parser/ScreenCommandParserTest.java

- Throw when there are too many/few arguments
- Take precedent of other errors, such as invalid index
- ViewCompanyCommand
- I removed missing index error, it does not make sense to use this error unless your validate the entity as well
- e.g. `view 1` will still return missing index error, even though it is the entity that is missing. 
- Missing/additional arguments (for command with fixed number of argument) will now all return invalid format error
- ScreenCommand
- Same as above
- Related to https://github.com/AY2425S1-CS2103-F13-4/tp/issues/150

Enforce checking of arguments count for Command with fixed number of arguments

---

src/main/java/seedu/address/logic/commands/EditCommand.java

Turns out there was indeed an elegant solution to the edit command issue.
To verify the correctness, let Ep refer to existing person in the list.
- If the changed field exists in Ep
- personToEdit and Ep will return true for `isSamePerson(editedPerson)` 
- Hence, `countDuplicates` = 2. Exception thrown
- If the changed field is unique
- `countDuplicates` = 1, pass first check
- `!personToEdit.isSamePerson(editedPerson)` = false, pass second check
- If the changed fields are unique
- `countDuplicates` = 0, clear that it passes both
- If the changed fields match Ep
- `countDuplicates` = 1, pass first check
- `!personToEdit.isSamePerson(editedPerson)` = true and `countDuplicates` = 1. Exception thrown  
- If the changed fields match Ep1 and Ep2 
- `countDuplicates` = 2. Exception thrown 
- …

Resolve issue #154

---

src/main/java/seedu/address/logic/commands/StatsCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java

- Import StatsCommand in AddressBookParser to handle the "stats" command.
- Add a new case in the parser’s switch statement to recognize and execute StatsCommand.
- Ensure that users can access the statistics functionality through the "stats" command in the UI.
Resolves issue #238

Add StatsCommand to AddressBookParser for command parsing

---

docs/DeveloperGuide.md

- closes #351
Issue: Reported functional bug where non-English (non-alphanumeric) name cannot be added. 
Solution: Specify in DG that our target user only deal with English for work

fix: Specify that our user only deal with English for work

---

src/main/java/seedu/address/logic/commands/AddContactCommand.java
src/main/java/seedu/address/logic/commands/DeleteContactCommand.java

- Closes #274
- Closes #304 
Does this violate feature freeze?  
Ans: No, because it is a strictly incorrect behaviour instead of a could be better. 
I give +1.5 for tester B.

fix: Incorrect success message for add and delete contact

---

docs/UserGuide.md

Remove the incorrect requirement in the User Guide that all lists must be
fully shown before using the `view company` command. Update documentation
to indicate that the command works regardless of
list visibility, aligning
it with actual functionality.
Closes #339

Fix incorrect UG statement for `view company` command

---

src/main/java/seedu/address/logic/commands/AddContactCommand.java
src/main/java/seedu/address/logic/commands/AddJobCommand.java
src/main/java/seedu/address/model/tag/Tag.java

- closes #281 
- closes #278 
- closes #329 
Tester B already had 1.5, I will give him another 0.5 for this. Note that this running count doesn't include my big PR so at the end will tally. 
Does this violate feature freeze?
Ans: No, refer to https://github.com/nus-cs2103-AY2425S1/forum/issues/663 which I raised.  
Converting skills/requirements to skill/requirement is fine as in the forum. 
Then converting Salary in UG to Monthly_Salary is a UG change (can go other way round too).
Lastly, error message for requirement is fine, since Tag is an outdated term.  
Edit: As an aside, is it a code quality issue if everything in the Tag class is `Tag`, but just that the error message was reworded to `Requirement`.

fix: Wrong messages for skill, requirement

---

src/main/java/seedu/address/logic/commands/EditCommand.java

- closes #357
This is strictly an incorrect behavior, edit a contact's email should not cause them to lose their job, therefore this is a functionality bug.

fix: Edit contact does not affect match

---

src/main/java/seedu/address/logic/commands/MatchCommand.java
src/main/java/seedu/address/logic/commands/ScreenCommand.java
src/main/java/seedu/address/logic/commands/UnmatchCommand.java

- closes #349 
- UG specify that the format of some commands such as `screen job` has the format of `screen job INDEX`, and the app display a different and incorrect format. 
- Related issue [Ben's forum question](https://github.com/nus-cs2103-AY2425S1/forum/issues/663)

Correct command format for some commands

---

docs/UserGuide.md

- closes #330
Kindly help to vet my English. Particularly I think the sentence is kind of awkward and could be better rephrased. 
Original sentence:
* The contacts role to job name matching is case-insensitive can be partial. e.g. Role `software engineer` will match to job name `Junior Java Software Engineer, Depart...`

330 pe dtester c screen job does not work as specified in ug

---

docs/UserGuide.md

- closes #296 
The tester misunderstood that we are specifying the job with the name of the job. 
Small change, I think without it the document is still strictly correct.

fix: Simplify screen job descriptin to make is clearer

---

src/main/resources/view/JobListCard.fxml
src/main/resources/view/PersonListCard.fxml

- Closes #373 
- Within it, closes #324 
- Within it, closes #321 
https://github.com/nus-cs2103-AY2425S1/forum/issues/629
Does this violate feature freeze? 
Ans: Probably not. Quote from Prof - "If you are asking if this can be fixed in v1.6, the answer is, 'only if there is no other way for the user to see the truncated part'".
For reasonable inputs, certain monitors are unable to see the jobMatchStatus or jobTitle. 
Company related stuff can be truncated too, HOWEVER, we can use view company to see the details, hence there are work arounds for it.
Was going to provide screenshots, but actually issues within #373 some testers already provided examples where at their full screen they couldn't see text.

Add wrapText to UI elements
